// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: api/codebase_syncer.proto

package codebase_syncer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SyncService_RegisterSync_FullMethodName     = "/codebase_syncer.SyncService/RegisterSync"
	SyncService_SyncCodebase_FullMethodName     = "/codebase_syncer.SyncService/SyncCodebase"
	SyncService_UnregisterSync_FullMethodName   = "/codebase_syncer.SyncService/UnregisterSync"
	SyncService_ShareAccessToken_FullMethodName = "/codebase_syncer.SyncService/ShareAccessToken"
	SyncService_GetVersion_FullMethodName       = "/codebase_syncer.SyncService/GetVersion"
	SyncService_CheckIgnoreFile_FullMethodName  = "/codebase_syncer.SyncService/CheckIgnoreFile"
)

// SyncServiceClient is the client API for SyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Sync service definition
type SyncServiceClient interface {
	// Register project sync
	RegisterSync(ctx context.Context, in *RegisterSyncRequest, opts ...grpc.CallOption) (*RegisterSyncResponse, error)
	// Sync project
	SyncCodebase(ctx context.Context, in *SyncCodebaseRequest, opts ...grpc.CallOption) (*SyncCodebaseResponse, error)
	// Unregister project sync
	UnregisterSync(ctx context.Context, in *UnregisterSyncRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Share AccessToken (plain text transmission, server-side encrypted storage)
	ShareAccessToken(ctx context.Context, in *ShareAccessTokenRequest, opts ...grpc.CallOption) (*ShareAccessTokenResponse, error)
	// Value application name and version information
	GetVersion(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
	// Check ignore file
	CheckIgnoreFile(ctx context.Context, in *CheckIgnoreFileRequest, opts ...grpc.CallOption) (*SyncCodebaseResponse, error)
}

type syncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncServiceClient(cc grpc.ClientConnInterface) SyncServiceClient {
	return &syncServiceClient{cc}
}

func (c *syncServiceClient) RegisterSync(ctx context.Context, in *RegisterSyncRequest, opts ...grpc.CallOption) (*RegisterSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterSyncResponse)
	err := c.cc.Invoke(ctx, SyncService_RegisterSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServiceClient) SyncCodebase(ctx context.Context, in *SyncCodebaseRequest, opts ...grpc.CallOption) (*SyncCodebaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncCodebaseResponse)
	err := c.cc.Invoke(ctx, SyncService_SyncCodebase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServiceClient) UnregisterSync(ctx context.Context, in *UnregisterSyncRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SyncService_UnregisterSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServiceClient) ShareAccessToken(ctx context.Context, in *ShareAccessTokenRequest, opts ...grpc.CallOption) (*ShareAccessTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShareAccessTokenResponse)
	err := c.cc.Invoke(ctx, SyncService_ShareAccessToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServiceClient) GetVersion(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, SyncService_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServiceClient) CheckIgnoreFile(ctx context.Context, in *CheckIgnoreFileRequest, opts ...grpc.CallOption) (*SyncCodebaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncCodebaseResponse)
	err := c.cc.Invoke(ctx, SyncService_CheckIgnoreFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncServiceServer is the server API for SyncService service.
// All implementations must embed UnimplementedSyncServiceServer
// for forward compatibility.
//
// Sync service definition
type SyncServiceServer interface {
	// Register project sync
	RegisterSync(context.Context, *RegisterSyncRequest) (*RegisterSyncResponse, error)
	// Sync project
	SyncCodebase(context.Context, *SyncCodebaseRequest) (*SyncCodebaseResponse, error)
	// Unregister project sync
	UnregisterSync(context.Context, *UnregisterSyncRequest) (*emptypb.Empty, error)
	// Share AccessToken (plain text transmission, server-side encrypted storage)
	ShareAccessToken(context.Context, *ShareAccessTokenRequest) (*ShareAccessTokenResponse, error)
	// Value application name and version information
	GetVersion(context.Context, *VersionRequest) (*VersionResponse, error)
	// Check ignore file
	CheckIgnoreFile(context.Context, *CheckIgnoreFileRequest) (*SyncCodebaseResponse, error)
	mustEmbedUnimplementedSyncServiceServer()
}

// UnimplementedSyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyncServiceServer struct{}

func (UnimplementedSyncServiceServer) RegisterSync(context.Context, *RegisterSyncRequest) (*RegisterSyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterSync not implemented")
}
func (UnimplementedSyncServiceServer) SyncCodebase(context.Context, *SyncCodebaseRequest) (*SyncCodebaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncCodebase not implemented")
}
func (UnimplementedSyncServiceServer) UnregisterSync(context.Context, *UnregisterSyncRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterSync not implemented")
}
func (UnimplementedSyncServiceServer) ShareAccessToken(context.Context, *ShareAccessTokenRequest) (*ShareAccessTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShareAccessToken not implemented")
}
func (UnimplementedSyncServiceServer) GetVersion(context.Context, *VersionRequest) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedSyncServiceServer) CheckIgnoreFile(context.Context, *CheckIgnoreFileRequest) (*SyncCodebaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckIgnoreFile not implemented")
}
func (UnimplementedSyncServiceServer) mustEmbedUnimplementedSyncServiceServer() {}
func (UnimplementedSyncServiceServer) testEmbeddedByValue()                     {}

// UnsafeSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncServiceServer will
// result in compilation errors.
type UnsafeSyncServiceServer interface {
	mustEmbedUnimplementedSyncServiceServer()
}

func RegisterSyncServiceServer(s grpc.ServiceRegistrar, srv SyncServiceServer) {
	// If the following call pancis, it indicates UnimplementedSyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SyncService_ServiceDesc, srv)
}

func _SyncService_RegisterSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).RegisterSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncService_RegisterSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).RegisterSync(ctx, req.(*RegisterSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncService_SyncCodebase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncCodebaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).SyncCodebase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncService_SyncCodebase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).SyncCodebase(ctx, req.(*SyncCodebaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncService_UnregisterSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).UnregisterSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncService_UnregisterSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).UnregisterSync(ctx, req.(*UnregisterSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncService_ShareAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).ShareAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncService_ShareAccessToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).ShareAccessToken(ctx, req.(*ShareAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncService_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).GetVersion(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncService_CheckIgnoreFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckIgnoreFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).CheckIgnoreFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncService_CheckIgnoreFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).CheckIgnoreFile(ctx, req.(*CheckIgnoreFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SyncService_ServiceDesc is the grpc.ServiceDesc for SyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "codebase_syncer.SyncService",
	HandlerType: (*SyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterSync",
			Handler:    _SyncService_RegisterSync_Handler,
		},
		{
			MethodName: "SyncCodebase",
			Handler:    _SyncService_SyncCodebase_Handler,
		},
		{
			MethodName: "UnregisterSync",
			Handler:    _SyncService_UnregisterSync_Handler,
		},
		{
			MethodName: "ShareAccessToken",
			Handler:    _SyncService_ShareAccessToken_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _SyncService_GetVersion_Handler,
		},
		{
			MethodName: "CheckIgnoreFile",
			Handler:    _SyncService_CheckIgnoreFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/codebase_syncer.proto",
}
