// Code generated by MockGen. DO NOT EDIT.
// Source: internal/client/llm.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	timeout "github.com/zgsm-ai/chat-rag/internal/timeout"
	types "github.com/zgsm-ai/chat-rag/internal/types"
	client "github.com/zgsm-ai/chat-rag/internal/client"
)

// MockLLMClientInterface is a mock of LLMClientInterface interface.
type MockLLMClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockLLMClientInterfaceMockRecorder
}

// MockLLMClientInterfaceMockRecorder is the mock recorder for MockLLMClientInterface.
type MockLLMClientInterfaceMockRecorder struct {
	mock *MockLLMClientInterface
}

// NewMockLLMClientInterface creates a new mock instance.
func NewMockLLMClientInterface(ctrl *gomock.Controller) *MockLLMClientInterface {
	mock := &MockLLMClientInterface{ctrl: ctrl}
	mock.recorder = &MockLLMClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMClientInterface) EXPECT() *MockLLMClientInterfaceMockRecorder {
	return m.recorder
}

// ChatLLMWithMessagesRaw mocks base method.
func (m *MockLLMClientInterface) ChatLLMWithMessagesRaw(ctx context.Context, params types.LLMRequestParams, idleTimer *timeout.IdleTimer) (types.ChatCompletionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatLLMWithMessagesRaw", ctx, params, idleTimer)
	ret0, _ := ret[0].(types.ChatCompletionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChatLLMWithMessagesRaw indicates an expected call of ChatLLMWithMessagesRaw.
func (mr *MockLLMClientInterfaceMockRecorder) ChatLLMWithMessagesRaw(ctx, params, idleTimer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatLLMWithMessagesRaw", reflect.TypeOf((*MockLLMClientInterface)(nil).ChatLLMWithMessagesRaw), ctx, params, idleTimer)
}

// ChatLLMWithMessagesStreamRaw mocks base method.
func (m *MockLLMClientInterface) ChatLLMWithMessagesStreamRaw(ctx context.Context, params types.LLMRequestParams, idleTimer *timeout.IdleTimer, callback func(client.LLMResponse) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatLLMWithMessagesStreamRaw", ctx, params, idleTimer, callback)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChatLLMWithMessagesStreamRaw indicates an expected call of ChatLLMWithMessagesStreamRaw.
func (mr *MockLLMClientInterfaceMockRecorder) ChatLLMWithMessagesStreamRaw(ctx, params, idleTimer, callback interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatLLMWithMessagesStreamRaw", reflect.TypeOf((*MockLLMClientInterface)(nil).ChatLLMWithMessagesStreamRaw), ctx, params, idleTimer, callback)
}

// GenerateContent mocks base method.
func (m *MockLLMClientInterface) GenerateContent(ctx context.Context, systemPrompt string, userMessages []types.Message) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateContent", ctx, systemPrompt, userMessages)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateContent indicates an expected call of GenerateContent.
func (mr *MockLLMClientInterfaceMockRecorder) GenerateContent(ctx, systemPrompt, userMessages interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateContent", reflect.TypeOf((*MockLLMClientInterface)(nil).GenerateContent), ctx, systemPrompt, userMessages)
}

// GetModelName mocks base method.
func (m *MockLLMClientInterface) GetModelName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetModelName indicates an expected call of GetModelName.
func (mr *MockLLMClientInterfaceMockRecorder) GetModelName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelName", reflect.TypeOf((*MockLLMClientInterface)(nil).GetModelName))
}

// SetTools mocks base method.
func (m *MockLLMClientInterface) SetTools(tools []types.Function) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTools", tools)
}

// SetTools indicates an expected call of SetTools.
func (mr *MockLLMClientInterfaceMockRecorder) SetTools(tools interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTools", reflect.TypeOf((*MockLLMClientInterface)(nil).SetTools), tools)
}
