// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/codegraph/proto/caller_info.proto

package codegraphpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CallerInfo 调用者信息
type CallerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SymbolName    string                 `protobuf:"bytes,1,opt,name=symbol_name,json=symbolName,proto3" json:"symbol_name,omitempty"`  // 符号名称
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`        // 文件路径
	Position      *Position              `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`                        // 位置信息
	ParamCount    int32                  `protobuf:"varint,4,opt,name=param_count,json=paramCount,proto3" json:"param_count,omitempty"` // 参数数量
	CalleeKey     *CalleeKey             `protobuf:"bytes,5,opt,name=callee_key,json=calleeKey,proto3" json:"callee_key,omitempty"`     // 被调用者的信息
	IsVariadic    bool                   `protobuf:"varint,6,opt,name=is_variadic,json=isVariadic,proto3" json:"is_variadic,omitempty"` // 调用者是否为可变参数
	Score         float64                `protobuf:"fixed64,7,opt,name=score,proto3" json:"score,omitempty"`                            // 评分
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallerInfo) Reset() {
	*x = CallerInfo{}
	mi := &file_pkg_codegraph_proto_caller_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallerInfo) ProtoMessage() {}

func (x *CallerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_codegraph_proto_caller_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallerInfo.ProtoReflect.Descriptor instead.
func (*CallerInfo) Descriptor() ([]byte, []int) {
	return file_pkg_codegraph_proto_caller_info_proto_rawDescGZIP(), []int{0}
}

func (x *CallerInfo) GetSymbolName() string {
	if x != nil {
		return x.SymbolName
	}
	return ""
}

func (x *CallerInfo) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *CallerInfo) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *CallerInfo) GetParamCount() int32 {
	if x != nil {
		return x.ParamCount
	}
	return 0
}

func (x *CallerInfo) GetCalleeKey() *CalleeKey {
	if x != nil {
		return x.CalleeKey
	}
	return nil
}

func (x *CallerInfo) GetIsVariadic() bool {
	if x != nil {
		return x.IsVariadic
	}
	return false
}

func (x *CallerInfo) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

// CalleeMapItem 被调用者映射项
type CalleeMapItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CalleeName    string                 `protobuf:"bytes,1,opt,name=callee_name,json=calleeName,proto3" json:"callee_name,omitempty"` // 被调用者名称，用于计算key
	Callers       []*CallerInfo          `protobuf:"bytes,2,rep,name=callers,proto3" json:"callers,omitempty"`                         // 调用者列表（数组）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalleeMapItem) Reset() {
	*x = CalleeMapItem{}
	mi := &file_pkg_codegraph_proto_caller_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalleeMapItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalleeMapItem) ProtoMessage() {}

func (x *CalleeMapItem) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_codegraph_proto_caller_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalleeMapItem.ProtoReflect.Descriptor instead.
func (*CalleeMapItem) Descriptor() ([]byte, []int) {
	return file_pkg_codegraph_proto_caller_info_proto_rawDescGZIP(), []int{1}
}

func (x *CalleeMapItem) GetCalleeName() string {
	if x != nil {
		return x.CalleeName
	}
	return ""
}

func (x *CalleeMapItem) GetCallers() []*CallerInfo {
	if x != nil {
		return x.Callers
	}
	return nil
}

// Position 位置信息
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartLine     int32                  `protobuf:"varint,1,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`       // 开始行（从1开始）
	StartColumn   int32                  `protobuf:"varint,2,opt,name=start_column,json=startColumn,proto3" json:"start_column,omitempty"` // 开始列（从1开始）
	EndLine       int32                  `protobuf:"varint,3,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`             // 结束行（从1开始）
	EndColumn     int32                  `protobuf:"varint,4,opt,name=end_column,json=endColumn,proto3" json:"end_column,omitempty"`       // 结束列（从1开始）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_pkg_codegraph_proto_caller_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_codegraph_proto_caller_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_pkg_codegraph_proto_caller_info_proto_rawDescGZIP(), []int{2}
}

func (x *Position) GetStartLine() int32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *Position) GetStartColumn() int32 {
	if x != nil {
		return x.StartColumn
	}
	return 0
}

func (x *Position) GetEndLine() int32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

func (x *Position) GetEndColumn() int32 {
	if x != nil {
		return x.EndColumn
	}
	return 0
}

// CalleeKey 被调用者的信息
type CalleeKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SymbolName    string                 `protobuf:"bytes,1,opt,name=symbol_name,json=symbolName,proto3" json:"symbol_name,omitempty"`  // 符号名称
	ParamCount    int32                  `protobuf:"varint,2,opt,name=param_count,json=paramCount,proto3" json:"param_count,omitempty"` // 参数数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalleeKey) Reset() {
	*x = CalleeKey{}
	mi := &file_pkg_codegraph_proto_caller_info_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalleeKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalleeKey) ProtoMessage() {}

func (x *CalleeKey) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_codegraph_proto_caller_info_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalleeKey.ProtoReflect.Descriptor instead.
func (*CalleeKey) Descriptor() ([]byte, []int) {
	return file_pkg_codegraph_proto_caller_info_proto_rawDescGZIP(), []int{3}
}

func (x *CalleeKey) GetSymbolName() string {
	if x != nil {
		return x.SymbolName
	}
	return ""
}

func (x *CalleeKey) GetParamCount() int32 {
	if x != nil {
		return x.ParamCount
	}
	return 0
}

var File_pkg_codegraph_proto_caller_info_proto protoreflect.FileDescriptor

const file_pkg_codegraph_proto_caller_info_proto_rawDesc = "" +
	"\n" +
	"%pkg/codegraph/proto/caller_info.proto\x12\vcodegraphpb\"\x8c\x02\n" +
	"\n" +
	"CallerInfo\x12\x1f\n" +
	"\vsymbol_name\x18\x01 \x01(\tR\n" +
	"symbolName\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x121\n" +
	"\bposition\x18\x03 \x01(\v2\x15.codegraphpb.PositionR\bposition\x12\x1f\n" +
	"\vparam_count\x18\x04 \x01(\x05R\n" +
	"paramCount\x125\n" +
	"\n" +
	"callee_key\x18\x05 \x01(\v2\x16.codegraphpb.CalleeKeyR\tcalleeKey\x12\x1f\n" +
	"\vis_variadic\x18\x06 \x01(\bR\n" +
	"isVariadic\x12\x14\n" +
	"\x05score\x18\a \x01(\x01R\x05score\"c\n" +
	"\rCalleeMapItem\x12\x1f\n" +
	"\vcallee_name\x18\x01 \x01(\tR\n" +
	"calleeName\x121\n" +
	"\acallers\x18\x02 \x03(\v2\x17.codegraphpb.CallerInfoR\acallers\"\x86\x01\n" +
	"\bPosition\x12\x1d\n" +
	"\n" +
	"start_line\x18\x01 \x01(\x05R\tstartLine\x12!\n" +
	"\fstart_column\x18\x02 \x01(\x05R\vstartColumn\x12\x19\n" +
	"\bend_line\x18\x03 \x01(\x05R\aendLine\x12\x1d\n" +
	"\n" +
	"end_column\x18\x04 \x01(\x05R\tendColumn\"M\n" +
	"\tCalleeKey\x12\x1f\n" +
	"\vsymbol_name\x18\x01 \x01(\tR\n" +
	"symbolName\x12\x1f\n" +
	"\vparam_count\x18\x02 \x01(\x05R\n" +
	"paramCountB-Z+pkg/codegraph/proto/codegraphpb;codegraphpbb\x06proto3"

var (
	file_pkg_codegraph_proto_caller_info_proto_rawDescOnce sync.Once
	file_pkg_codegraph_proto_caller_info_proto_rawDescData []byte
)

func file_pkg_codegraph_proto_caller_info_proto_rawDescGZIP() []byte {
	file_pkg_codegraph_proto_caller_info_proto_rawDescOnce.Do(func() {
		file_pkg_codegraph_proto_caller_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_codegraph_proto_caller_info_proto_rawDesc), len(file_pkg_codegraph_proto_caller_info_proto_rawDesc)))
	})
	return file_pkg_codegraph_proto_caller_info_proto_rawDescData
}

var file_pkg_codegraph_proto_caller_info_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_codegraph_proto_caller_info_proto_goTypes = []any{
	(*CallerInfo)(nil),    // 0: codegraphpb.CallerInfo
	(*CalleeMapItem)(nil), // 1: codegraphpb.CalleeMapItem
	(*Position)(nil),      // 2: codegraphpb.Position
	(*CalleeKey)(nil),     // 3: codegraphpb.CalleeKey
}
var file_pkg_codegraph_proto_caller_info_proto_depIdxs = []int32{
	2, // 0: codegraphpb.CallerInfo.position:type_name -> codegraphpb.Position
	3, // 1: codegraphpb.CallerInfo.callee_key:type_name -> codegraphpb.CalleeKey
	0, // 2: codegraphpb.CalleeMapItem.callers:type_name -> codegraphpb.CallerInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_codegraph_proto_caller_info_proto_init() }
func file_pkg_codegraph_proto_caller_info_proto_init() {
	if File_pkg_codegraph_proto_caller_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_codegraph_proto_caller_info_proto_rawDesc), len(file_pkg_codegraph_proto_caller_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_codegraph_proto_caller_info_proto_goTypes,
		DependencyIndexes: file_pkg_codegraph_proto_caller_info_proto_depIdxs,
		MessageInfos:      file_pkg_codegraph_proto_caller_info_proto_msgTypes,
	}.Build()
	File_pkg_codegraph_proto_caller_info_proto = out.File
	file_pkg_codegraph_proto_caller_info_proto_goTypes = nil
	file_pkg_codegraph_proto_caller_info_proto_depIdxs = nil
}
