// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: pkg/codegraph/proto/file_element.proto

package codegraphpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FileElementTable 文件元素表，简化版本
type FileElementTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Imports       []*Import              `protobuf:"bytes,4,rep,name=imports,proto3" json:"imports,omitempty"`
	Package       *Package               `protobuf:"bytes,5,opt,name=package,proto3" json:"package,omitempty"`
	Elements      []*Element             `protobuf:"bytes,6,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileElementTable) Reset() {
	*x = FileElementTable{}
	mi := &file_pkg_codegraph_proto_file_element_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileElementTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileElementTable) ProtoMessage() {}

func (x *FileElementTable) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_codegraph_proto_file_element_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileElementTable.ProtoReflect.Descriptor instead.
func (*FileElementTable) Descriptor() ([]byte, []int) {
	return file_pkg_codegraph_proto_file_element_proto_rawDescGZIP(), []int{0}
}

func (x *FileElementTable) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileElementTable) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *FileElementTable) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *FileElementTable) GetImports() []*Import {
	if x != nil {
		return x.Imports
	}
	return nil
}

func (x *FileElementTable) GetPackage() *Package {
	if x != nil {
		return x.Package
	}
	return nil
}

func (x *FileElementTable) GetElements() []*Element {
	if x != nil {
		return x.Elements
	}
	return nil
}

// 导入
type Import struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Alias         string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	Range         []int32                `protobuf:"varint,4,rep,packed,name=range,proto3" json:"range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Import) Reset() {
	*x = Import{}
	mi := &file_pkg_codegraph_proto_file_element_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Import) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Import) ProtoMessage() {}

func (x *Import) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_codegraph_proto_file_element_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Import.ProtoReflect.Descriptor instead.
func (*Import) Descriptor() ([]byte, []int) {
	return file_pkg_codegraph_proto_file_element_proto_rawDescGZIP(), []int{1}
}

func (x *Import) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Import) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Import) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Import) GetRange() []int32 {
	if x != nil {
		return x.Range
	}
	return nil
}

// 包
type Package struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Range         []int32                `protobuf:"varint,2,rep,packed,name=range,proto3" json:"range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Package) Reset() {
	*x = Package{}
	mi := &file_pkg_codegraph_proto_file_element_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_codegraph_proto_file_element_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_pkg_codegraph_proto_file_element_proto_rawDescGZIP(), []int{2}
}

func (x *Package) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Package) GetRange() []int32 {
	if x != nil {
		return x.Range
	}
	return nil
}

// Element 代码元素定义
type Element struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDefinition  bool                   `protobuf:"varint,2,opt,name=is_definition,json=isDefinition,proto3" json:"is_definition,omitempty"`
	ElementType   ElementType            `protobuf:"varint,3,opt,name=element_type,json=elementType,proto3,enum=codegraphpb.ElementType" json:"element_type,omitempty"`
	Range         []int32                `protobuf:"varint,4,rep,packed,name=range,proto3" json:"range,omitempty"`
	ExtraData     map[string][]byte      `protobuf:"bytes,6,rep,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Element) Reset() {
	*x = Element{}
	mi := &file_pkg_codegraph_proto_file_element_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Element) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Element) ProtoMessage() {}

func (x *Element) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_codegraph_proto_file_element_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Element.ProtoReflect.Descriptor instead.
func (*Element) Descriptor() ([]byte, []int) {
	return file_pkg_codegraph_proto_file_element_proto_rawDescGZIP(), []int{3}
}

func (x *Element) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Element) GetIsDefinition() bool {
	if x != nil {
		return x.IsDefinition
	}
	return false
}

func (x *Element) GetElementType() ElementType {
	if x != nil {
		return x.ElementType
	}
	return ElementType_UNDEFINED
}

func (x *Element) GetRange() []int32 {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *Element) GetExtraData() map[string][]byte {
	if x != nil {
		return x.ExtraData
	}
	return nil
}

var File_pkg_codegraph_proto_file_element_proto protoreflect.FileDescriptor

const file_pkg_codegraph_proto_file_element_proto_rawDesc = "" +
	"\n" +
	"&pkg/codegraph/proto/file_element.proto\x12\vcodegraphpb\x1a\x1fpkg/codegraph/proto/types.proto\"\xf1\x01\n" +
	"\x10FileElementTable\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12-\n" +
	"\aimports\x18\x04 \x03(\v2\x13.codegraphpb.ImportR\aimports\x12.\n" +
	"\apackage\x18\x05 \x01(\v2\x14.codegraphpb.PackageR\apackage\x120\n" +
	"\belements\x18\x06 \x03(\v2\x14.codegraphpb.ElementR\belements\"`\n" +
	"\x06Import\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\x12\x14\n" +
	"\x05range\x18\x04 \x03(\x05R\x05range\"3\n" +
	"\aPackage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05range\x18\x02 \x03(\x05R\x05range\"\x97\x02\n" +
	"\aElement\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\ris_definition\x18\x02 \x01(\bR\fisDefinition\x12;\n" +
	"\felement_type\x18\x03 \x01(\x0e2\x18.codegraphpb.ElementTypeR\velementType\x12\x14\n" +
	"\x05range\x18\x04 \x03(\x05R\x05range\x12B\n" +
	"\n" +
	"extra_data\x18\x06 \x03(\v2#.codegraphpb.Element.ExtraDataEntryR\textraData\x1a<\n" +
	"\x0eExtraDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01B-Z+pkg/codegraph/proto/codegraphpb;codegraphpbb\x06proto3"

var (
	file_pkg_codegraph_proto_file_element_proto_rawDescOnce sync.Once
	file_pkg_codegraph_proto_file_element_proto_rawDescData []byte
)

func file_pkg_codegraph_proto_file_element_proto_rawDescGZIP() []byte {
	file_pkg_codegraph_proto_file_element_proto_rawDescOnce.Do(func() {
		file_pkg_codegraph_proto_file_element_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_codegraph_proto_file_element_proto_rawDesc), len(file_pkg_codegraph_proto_file_element_proto_rawDesc)))
	})
	return file_pkg_codegraph_proto_file_element_proto_rawDescData
}

var file_pkg_codegraph_proto_file_element_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_codegraph_proto_file_element_proto_goTypes = []any{
	(*FileElementTable)(nil), // 0: codegraphpb.FileElementTable
	(*Import)(nil),           // 1: codegraphpb.Import
	(*Package)(nil),          // 2: codegraphpb.Package
	(*Element)(nil),          // 3: codegraphpb.Element
	nil,                      // 4: codegraphpb.Element.ExtraDataEntry
	(ElementType)(0),         // 5: codegraphpb.ElementType
}
var file_pkg_codegraph_proto_file_element_proto_depIdxs = []int32{
	1, // 0: codegraphpb.FileElementTable.imports:type_name -> codegraphpb.Import
	2, // 1: codegraphpb.FileElementTable.package:type_name -> codegraphpb.Package
	3, // 2: codegraphpb.FileElementTable.elements:type_name -> codegraphpb.Element
	5, // 3: codegraphpb.Element.element_type:type_name -> codegraphpb.ElementType
	4, // 4: codegraphpb.Element.extra_data:type_name -> codegraphpb.Element.ExtraDataEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_codegraph_proto_file_element_proto_init() }
func file_pkg_codegraph_proto_file_element_proto_init() {
	if File_pkg_codegraph_proto_file_element_proto != nil {
		return
	}
	file_pkg_codegraph_proto_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_codegraph_proto_file_element_proto_rawDesc), len(file_pkg_codegraph_proto_file_element_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_codegraph_proto_file_element_proto_goTypes,
		DependencyIndexes: file_pkg_codegraph_proto_file_element_proto_depIdxs,
		MessageInfos:      file_pkg_codegraph_proto_file_element_proto_msgTypes,
	}.Build()
	File_pkg_codegraph_proto_file_element_proto = out.File
	file_pkg_codegraph_proto_file_element_proto_goTypes = nil
	file_pkg_codegraph_proto_file_element_proto_depIdxs = nil
}
