// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: pkg/codegraph/proto/symbol_definition.proto

package codegraphpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SymbolDefinition 符号定义
type SymbolOccurrence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Occurrences   []*Occurrence          `protobuf:"bytes,3,rep,name=occurrences,proto3" json:"occurrences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymbolOccurrence) Reset() {
	*x = SymbolOccurrence{}
	mi := &file_pkg_codegraph_proto_symbol_definition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolOccurrence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolOccurrence) ProtoMessage() {}

func (x *SymbolOccurrence) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_codegraph_proto_symbol_definition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolOccurrence.ProtoReflect.Descriptor instead.
func (*SymbolOccurrence) Descriptor() ([]byte, []int) {
	return file_pkg_codegraph_proto_symbol_definition_proto_rawDescGZIP(), []int{0}
}

func (x *SymbolOccurrence) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SymbolOccurrence) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SymbolOccurrence) GetOccurrences() []*Occurrence {
	if x != nil {
		return x.Occurrences
	}
	return nil
}

// Definition 定义详情
type Occurrence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Range         []int32                `protobuf:"varint,2,rep,packed,name=range,proto3" json:"range,omitempty"`
	ElementType   ElementType            `protobuf:"varint,3,opt,name=element_type,json=elementType,proto3,enum=codegraphpb.ElementType" json:"element_type,omitempty"`
	RelationType  RelationType           `protobuf:"varint,4,opt,name=relation_type,json=relationType,proto3,enum=codegraphpb.RelationType" json:"relation_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Occurrence) Reset() {
	*x = Occurrence{}
	mi := &file_pkg_codegraph_proto_symbol_definition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Occurrence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Occurrence) ProtoMessage() {}

func (x *Occurrence) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_codegraph_proto_symbol_definition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Occurrence.ProtoReflect.Descriptor instead.
func (*Occurrence) Descriptor() ([]byte, []int) {
	return file_pkg_codegraph_proto_symbol_definition_proto_rawDescGZIP(), []int{1}
}

func (x *Occurrence) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Occurrence) GetRange() []int32 {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *Occurrence) GetElementType() ElementType {
	if x != nil {
		return x.ElementType
	}
	return ElementType_UNDEFINED
}

func (x *Occurrence) GetRelationType() RelationType {
	if x != nil {
		return x.RelationType
	}
	return RelationType_RELATION_UNDEFINED
}

var File_pkg_codegraph_proto_symbol_definition_proto protoreflect.FileDescriptor

const file_pkg_codegraph_proto_symbol_definition_proto_rawDesc = "" +
	"\n" +
	"+pkg/codegraph/proto/symbol_definition.proto\x12\vcodegraphpb\x1a\x1fpkg/codegraph/proto/types.proto\"}\n" +
	"\x10SymbolOccurrence\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x129\n" +
	"\voccurrences\x18\x03 \x03(\v2\x17.codegraphpb.OccurrenceR\voccurrences\"\xb3\x01\n" +
	"\n" +
	"Occurrence\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05range\x18\x02 \x03(\x05R\x05range\x12;\n" +
	"\felement_type\x18\x03 \x01(\x0e2\x18.codegraphpb.ElementTypeR\velementType\x12>\n" +
	"\rrelation_type\x18\x04 \x01(\x0e2\x19.codegraphpb.RelationTypeR\frelationTypeB-Z+pkg/codegraph/proto/codegraphpb;codegraphpbb\x06proto3"

var (
	file_pkg_codegraph_proto_symbol_definition_proto_rawDescOnce sync.Once
	file_pkg_codegraph_proto_symbol_definition_proto_rawDescData []byte
)

func file_pkg_codegraph_proto_symbol_definition_proto_rawDescGZIP() []byte {
	file_pkg_codegraph_proto_symbol_definition_proto_rawDescOnce.Do(func() {
		file_pkg_codegraph_proto_symbol_definition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_codegraph_proto_symbol_definition_proto_rawDesc), len(file_pkg_codegraph_proto_symbol_definition_proto_rawDesc)))
	})
	return file_pkg_codegraph_proto_symbol_definition_proto_rawDescData
}

var file_pkg_codegraph_proto_symbol_definition_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_codegraph_proto_symbol_definition_proto_goTypes = []any{
	(*SymbolOccurrence)(nil), // 0: codegraphpb.SymbolOccurrence
	(*Occurrence)(nil),       // 1: codegraphpb.Occurrence
	(ElementType)(0),         // 2: codegraphpb.ElementType
	(RelationType)(0),        // 3: codegraphpb.RelationType
}
var file_pkg_codegraph_proto_symbol_definition_proto_depIdxs = []int32{
	1, // 0: codegraphpb.SymbolOccurrence.occurrences:type_name -> codegraphpb.Occurrence
	2, // 1: codegraphpb.Occurrence.element_type:type_name -> codegraphpb.ElementType
	3, // 2: codegraphpb.Occurrence.relation_type:type_name -> codegraphpb.RelationType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_codegraph_proto_symbol_definition_proto_init() }
func file_pkg_codegraph_proto_symbol_definition_proto_init() {
	if File_pkg_codegraph_proto_symbol_definition_proto != nil {
		return
	}
	file_pkg_codegraph_proto_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_codegraph_proto_symbol_definition_proto_rawDesc), len(file_pkg_codegraph_proto_symbol_definition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_codegraph_proto_symbol_definition_proto_goTypes,
		DependencyIndexes: file_pkg_codegraph_proto_symbol_definition_proto_depIdxs,
		MessageInfos:      file_pkg_codegraph_proto_symbol_definition_proto_msgTypes,
	}.Build()
	File_pkg_codegraph_proto_symbol_definition_proto = out.File
	file_pkg_codegraph_proto_symbol_definition_proto_goTypes = nil
	file_pkg_codegraph_proto_symbol_definition_proto_depIdxs = nil
}
